---
- name: VPN | Configuration | Allow IP forwarding for IPv4
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    reload: yes

- name: VPN | Configuration | Allow iptables input port
  iptables:
    table: filter
    chain: INPUT
    protocol: "{{ protocol }}"
    destination_port: "{{ server_port }}"
    jump: ACCEPT
  become: yes
  when: iptables_configure
  tags:
    - iptables

- name: VPN | Configuration | Allow iptables vnet source
  iptables:
    table: filter
    chain: INPUT
    source: "{{ vpn_network }}/{{ vpn_cidr }}"
    jump: ACCEPT
  become: yes
  when: iptables_configure
  tags:
    - iptables

- name: VPN | Configuration | Allow iptables forward
  iptables:
    table: filter
    chain: FORWARD
    source: "{{ vpn_network }}/{{ vpn_cidr }}"
    jump: ACCEPT
  become: yes
  when: iptables_configure
  tags:
    - iptables

- name: VPN | Configuration | Allow iptables postrouting
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ vpn_network }}/{{ vpn_cidr }}"
    jump: MASQUERADE
  become: yes
  when: iptables_configure and allow_masquerade
  tags:
    - iptables

- name: VPN | Configuration | Save iptables rules
  shell: "iptables-save > /etc/iptables/rules.v4"
  when: iptables_configure
  tags:
    - iptables

- name: VPN | Configuration | Ensure pam configuration for 2fa
  template:
    src: openvpn.2fa
    dest: /etc/pam.d/openvpn
    owner: root
    group: root
    mode: 0644
  when: enable_2fa
  tags:
    - 2fa
